#!/bin/bash
# Helper script to clean up old nightly packages from
# git-lfs repo. Should be run manually occasionally.
set -e
set -u
# Don't use pipefail, because the 'grep' command that filters
# for nightly '-dev-' packages may return none (e.g. for securedrop-keyring)
# set -o pipefail


limit="${1:-10}"
echo "Will remove all but the newest $limit nightlies for each package."

# For now, we only build nightlies for workstation/buster, so just
# look at that directory.
d="workstation/buster"
pushd "$d" > /dev/null
while read -r pkg ; do
    # Only process nightlies, otherwise skip.
    pkgs="$(find . | grep "$pkg" | grep '\-dev\-' | sort -n)"
    # Use -w instead of -l so empty output is understood as 0.
    num_pkgs="$(wc -w <<< "$pkgs")"
    i="$num_pkgs"
    if [[ $num_pkgs -gt $limit ]]; then
        echo "Removing $(( num_pkgs - limit )) packages for $pkg ..."
        while read -r p; do
            if [[ $i -gt $limit ]]; then
                git rm -q "$p"
                i="$((i-1))"
            fi
        done <<< "$pkgs"
    else
        echo "Removing 0 packages for ${pkg}, found ${num_pkgs}/${limit} nightlies"
    fi
# Find all package names before underscore, filter for uniqueness,
# then select only the 'securedrop*' packages, skipping e.g. kernel images.
done < <(find . -mindepth 1 -type f -iname 'securedrop*.deb' | cut -f1 -d_ | sort -u)
popd > /dev/null
