name: Publish to R2
# Trigger on pushes to main that modify repo/public/
on:
  push:
    branches:
      - main
    paths:
      - 'repo/public/**'

jobs:
  publish:
    uses: freedomofpress/actionslib/.github/workflows/publish-r2.yaml@main
    with:
      path: repo/public/
      lfs: true
    secrets:
      R2_ACCESS_KEY_ID: ${{ secrets.TEST_R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.TEST_R2_SECRET_ACCESS_KEY }}
      R2_ACCOUNT_ID: ${{ secrets.TEST_R2_ACCOUNT_ID }}
      R2_BUCKET: ${{ secrets.TEST_R2_BUCKET }}
